import { useCallback, useEffect, useState } from 'react'
import { App, Button, Card, Form, Input, InputNumber, Modal, Space, Table, Tag } from 'antd'
import { PlusOutlined, ReloadOutlined } from '@ant-design/icons'
import { api } from '../api'

type Line={id:number;lineNo:string;host:string;port:number;enabled:boolean;priority:number;capacity:number;activeCalls:number;available:boolean;circuitState:string;failureStreak:number;openedUntil:string}
type Event={id:number;lineNo:string;callId:number;fromState:string;toState:string;reason:string;createdAt:string}
export default function Lines(){const {message}=App.useApp();const [lines,setLines]=useState<Line[]>([]);const [events,setEvents]=useState<Event[]>([]);const [open,setOpen]=useState(false);const [form]=Form.useForm();
 const load=useCallback(async()=>{const [a,b]=await Promise.all([api.get<Line[]>('/api/monitor/lines'),api.get<Event[]>('/api/monitor/line-events')]);if(a.success)setLines(a.data||[]);if(b.success)setEvents(b.data||[])},[]);useEffect(()=>{load()},[load]);
 const save=async(v:Record<string,unknown>)=>{const r=await api.post('/api/monitor/lines',v);if(!r.success){message.error(r.message);return}message.success(r.message);setOpen(false);form.resetFields();load()}
 return <Space direction="vertical" style={{width:'100%'}}><Card title="外呼线路" extra={<Space><Button icon={<ReloadOutlined/>} onClick={load}>刷新</Button><Button type="primary" icon={<PlusOutlined/>} onClick={()=>setOpen(true)}>新增线路</Button></Space>}><Table rowKey="id" dataSource={lines} columns={[{title:'线路',dataIndex:'lineNo'},{title:'SIP地址',render:(_,r)=><>{r.host}:{r.port}</>},{title:'状态',render:(_,r)=><Tag color={r.enabled?'green':'default'}>{r.enabled?'启用':'停用'}</Tag>},{title:'熔断',render:(_,r)=><Tag color={r.circuitState==='OPEN'?'red':r.circuitState==='HALF_OPEN'?'orange':'green'}>{r.circuitState} / {r.failureStreak}</Tag>},{title:'容量',render:(_,r)=><>{r.activeCalls} / {r.capacity}</>},{title:'优先级',dataIndex:'priority'},{title:'恢复时间',dataIndex:'openedUntil'}]}/></Card><Card title="熔断事件时间线"><Table rowKey="id" dataSource={events} pagination={{pageSize:10}} columns={[{title:'时间',dataIndex:'createdAt'},{title:'线路',dataIndex:'lineNo'},{title:'话务',dataIndex:'callId'},{title:'状态',render:(_,r)=><>{r.fromState} → {r.toState}</>},{title:'原因',dataIndex:'reason'}]}/></Card><Modal title="新增外呼线路" open={open} onCancel={()=>setOpen(false)} onOk={()=>form.submit()}><Form form={form} onFinish={save} layout="vertical"><Form.Item name="lineNo" label="线路号码" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="host" label="SIP 主机"><Input/></Form.Item><Form.Item name="port" label="端口" initialValue={5060}><InputNumber min={1} max={65535} style={{width:'100%'}}/></Form.Item><Form.Item name="priority" label="优先级" initialValue={100}><InputNumber min={1} style={{width:'100%'}}/></Form.Item><Form.Item name="capacity" label="并发容量" initialValue={10}><InputNumber min={1} style={{width:'100%'}}/></Form.Item></Form></Modal></Space>}
